//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshChoice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressId { get; set; }
        public string AddressName { get; set; }
        public string AddressDescription { get; set; }
        public double AddressLongitude { get; set; }
        public double AddressLatitude { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
