//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshChoice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int DeliveryId { get; set; }
        public string DeliveryType { get; set; }
    }
}
