//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshChoice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageId { get; set; }
        public byte[] ImageBlob { get; set; }
        public string ImageUrl { get; set; }
        public string ImageDescription { get; set; }
        public int ItemId { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
