//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshChoice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public string TransactionDescription { get; set; }
        public double TransactionAmount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int WalletId { get; set; }
    
        public virtual Wallet Wallet { get; set; }
    }
}
